title = "Input"

[home]
enabled = true
includeReadme = true

[docusaurus]
url = "https://input.pages.dev/"
baseUrl = "/"
tagline = "A Roblox module for handling user input on the server."
onBrokenLinks = "warn"